name: rsshub

services:
  rsshub:
    image: rsshub
    build:
      context: .
      args:
        PUPPETEER_SKIP_DOWNLOAD: 0
    restart: always
    ports:
      - "1200:1200"
    environment:
      NODE_ENV: production
      CACHE_TYPE: redis
      REDIS_URL: "redis://rss-redis:6379/"
    networks:
      - ai-service
    depends_on:
      - redis

  redis:
    container_name: rss-redis
    image: redis:alpine
    restart: always
    volumes:
      - ./redis_data:/data
    networks:
      - ai-service
    deploy:
      resources:
        limits:
          memory: 64M

networks:
  ai-service:
    external: true